#https://docs.codacy.com/
# Code quality analysis tool configuration file for Codacy
engines:
  pylint:
    enabled: true
    config:
      file: .pylintrc

exclude_paths:
  - docs/source/conf.py
  - .github/**
  - scripts/**
